using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ReQuestyGenerated;

/// <inheritdoc />
[Generator]
public class ReQuestyVersionGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, (spc, compilation) =>
        {
            string projectDirectory = Path.GetDirectoryName(compilation.SyntaxTrees.First().FilePath);

            try
            {
                XmlDocument csproj = new();
                projectDirectory = Path.GetFullPath(Path.Combine(projectDirectory, "..", "ReQuesty.Runtime.csproj"));
                csproj.Load(projectDirectory);
                string version = csproj.GetElementsByTagName("Version")[0].InnerText;
                string source = $@"// <auto-generated/>
namespace ReQuesty.Runtime.Generated;

/// <summary>
///   The version class
/// </summary>
public static class Version
{{
    /// <summary>
    ///   The current version string
    /// </summary>
    public static string Current()
    {{
        return ""{version}"";
    }}
}}
";

                // Add the source code to the compilation
                spc.AddSource($"ReQuestyVersion.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception e)
            {
                throw new FileNotFoundException($"ReQuestyVersionGenerator expanded in an invalid project, missing 'csproj' file in the following directory {projectDirectory}, {e.Message}", e);
            }
        });
    }
}
